FROM ubuntu:22.04
ENV PATH=${PATH}:/usr/local/go/bin:/opt/workdir/.go/bin
ENV GOPATH=/opt/workdir/.go
ENV GOCACHE=/opt/workdir/.go/.cache
WORKDIR /opt/workdir
RUN apt update -y \
    && apt install wget make gcc -y \
    && wget https://go.dev/dl/go1.19.3.linux-arm64.tar.gz \
    && rm -rf /usr/local/go \
    && tar -C /usr/local -xzf go1.19.3.linux-arm64.tar.gz \
    && mkdir -p /opt/workdir/.go/github.com \
    && rm -fr go1.19.3.linux-arm64.tar.gz \
    && go install github.com/go-delve/delve/cmd/dlv@latest
CMD ["/bin/bash", "-c", "sleep inf"]