apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-gpu-1
spec:
  selector:
    matchLabels:
      app: mnist-gpu-1
  template:
    metadata:
      labels:
        app: mnist-gpu-1
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: mnist-gpu-1
        image: tensorflow/tensorflow:latest-gpu
        command:
          - /bin/bash
          - -c
          - sleep inf
        resources:
          limits:
            nvidia.com/gpu: "2"
        volumeMounts:
        - name: lib
          mountPath: /lib/hostlibs
        env:
          - name: LD_LIBRARY_PATH
            value: /lib/hostlibs
      volumes:
      - name: lib
        hostPath:
          path: /lib/x86_64-linux-gnu/
          type: Directory