apiVersion: v1
kind: Pod
metadata:
  name: ramdisk-plugin
  namespace: cnvrg
  labels:
    app: ramdisk-plugin
spec:
  containers:
  - name: ramdisk-plugin
    imagePullPolicy: Always
    image: cnvrg/ramdisk-plugin-dvl:latest
    ports:
    - containerPort: 2345
    securityContext:
      privileged: true
    volumeMounts:
      - name: device-plugin
        mountPath: /var/lib/kubelet/device-plugins
  volumes:
    - name: device-plugin
      hostPath:
        path: /var/lib/kubelet/device-plugins
---
apiVersion: v1
kind: Service
metadata:
  name: ramdisk-plugin
  namespace: cnvrg
spec:
  type: NodePort
  selector:
    app: ramdisk-plugin
  ports:
    - protocol: TCP
      port: 2345
      targetPort: 2345
      nodePort: 30000