apiVersion: v1
kind: Pod
metadata:
  name: ramdisk-pod-test
  namespace: cnvrg
  labels:
    app: ramdisk-pod-test
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      limits:
        cnvrg.io/ramdisk: "1"
